import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "../providers/authProvider";
import { getServerSession } from "next-auth/next";
import { GET as handler } from "@/app/api/auth/[...nextauth]/route";
import { Nav } from "./nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/static/favicon.ico",
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(handler);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider session={session}>
          <Nav />
          {children}
        </Provider>
      </body>
    </html>
  );
}
